
/**************************************************************
 *	
 *	GameSong, 8 bit, 11025Hz,
 *	1 channel, 195382 bytes/channel
 *	Total Size: 1 * 195382 + 4 (header) = 195426 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sarah\Documents\School\2017 Spring\CS 2261\Lab9_SarahVeith\LAB09_Sound\GameSong.wav
 *	Time-stamp: Wed Mar 29 18:21:34 2017
 *	
 **************************************************************/

#ifndef __GAMESONGH__
#define __GAMESONGH__

#define GAMESONGFREQ 11025
#define GAMESONGLEN 195382

extern const unsigned char GameSong[195382];

#endif /* __GAMESONGH__ */
