
/**************************************************************
 *	
 *	StartSFX, 8 bit, 11025Hz,
 *	1 channel, 127296 bytes/channel
 *	Total Size: 1 * 127296 + 4 (header) = 127340 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sarah\Documents\School\2017 Spring\CS 2261\Lab9_SarahVeith\LAB09_Sound\StartSFX.wav
 *	Time-stamp: Wed Mar 29 18:21:43 2017
 *	
 **************************************************************/

#ifndef __STARTSFXH__
#define __STARTSFXH__

#define STARTSFXFREQ 11025
#define STARTSFXLEN 127296

extern const unsigned char StartSFX[127296];

#endif /* __STARTSFXH__ */
