
/**************************************************************
 *	
 *	TitleSong, 8 bit, 11025Hz,
 *	1 channel, 447027 bytes/channel
 *	Total Size: 1 * 447027 + 4 (header) = 447071 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sarah\Documents\School\2017 Spring\CS 2261\Lab9_SarahVeith\LAB09_Sound\TitleSong.wav
 *	Time-stamp: Wed Mar 29 18:21:49 2017
 *	
 **************************************************************/

#ifndef __TITLESONGH__
#define __TITLESONGH__

#define TITLESONGFREQ 11025
#define TITLESONGLEN 447027

extern const unsigned char TitleSong[447027];

#endif /* __TITLESONGH__ */
