
/**************************************************************
 *	
 *	chaChing, 8 bit, 11025Hz,
 *	1 channel, 8773 bytes/channel
 *	Total Size: 1 * 8773 + 4 (header) = 8817 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\vicki\cs2261\FinalProject\M04\chaChing.wav
 *	Time-stamp: Thu Apr 18 17:47:52 2019
 *	
 **************************************************************/

#ifndef __CHACHINGH__
#define __CHACHINGH__

#define CHACHINGFREQ 11025
#define CHACHINGLEN 8773

extern const unsigned char chaChing[8773];

#endif /* __CHACHINGH__ */
