
/**************************************************************
 *	
 *	cheering, 8 bit, 11025Hz,
 *	1 channel, 496125 bytes/channel
 *	Total Size: 1 * 496125 + 4 (header) = 496169 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\vicki\cs2261\FinalProject\cheering.wav
 *	Time-stamp: Fri Apr 26 11:18:50 2019
 *	
 **************************************************************/

#ifndef __CHEERINGH__
#define __CHEERINGH__

#define CHEERINGFREQ 11025
#define CHEERINGLEN 496125

extern const unsigned char cheering[496125];

#endif /* __CHEERINGH__ */
