
/**************************************************************
 *	
 *	softJazz, 8 bit, 11025Hz,
 *	1 channel, 330750 bytes/channel
 *	Total Size: 1 * 330750 + 4 (header) = 330794 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\vicki\cs2261\FinalProject\M04\softJazz.wav
 *	Time-stamp: Thu Apr 18 17:51:01 2019
 *	
 **************************************************************/

#ifndef __SOFTJAZZH__
#define __SOFTJAZZH__

#define SOFTJAZZFREQ 11025
#define SOFTJAZZLEN 330750

extern const unsigned char softJazz[330750];

#endif /* __SOFTJAZZH__ */
